server:
  port: 8082
spring:
  application:
    name: userprovider
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&&characterEncoding=utf-8&&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka/,http://localhost:8182/eureka/
